version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=gradeportal
      - POSTGRES_PASSWORD=cs130gp
      - PGDATA=/pgdata
  api:
    build: 
      context: ./api
    volumes: 
      - ./api:/go/src/github.com/jcherianucla/UCLA-CS-130/api
    ports:
      - "5000:8080"
    links:
      - db

